package lucidegen

import (
	"os"
	"strings"
	"text/template"
	"time"
)

// Template for individual icon components
const iconsTemplate = `// Code generated by lucide-templ-gen on {{.Timestamp}}. DO NOT EDIT.
// Source: https://github.com/lucide-icons/lucide
// Generator: https://github.com/peterszarvas94/lucide-templ-gen

package {{.PackageName}}

{{range .Icons}}
// {{.FuncName}} renders the {{.Name}} Lucide icon
templ {{.FuncName}}(attrs templ.Attributes) {
	<svg viewBox="{{.ViewBox}}" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" { attrs... }>
		{{.Content}}
	</svg>
}
{{end}}`

// Template for icon registry
const registryTemplate = `// Code generated by lucide-templ-gen on {{.Timestamp}}. DO NOT EDIT.

package {{.PackageName}}

// IconName represents a valid Lucide icon name
type IconName string

// Icon name constants
const (
{{range .Icons}}	{{call $.ToConstantName .Name $.Prefix}} IconName = "{{.Name}}"
{{end}})

// Icon renders any Lucide icon by name with type safety
templ Icon(name IconName, attrs templ.Attributes) {
	switch name {
{{range .Icons}}	case {{call $.ToConstantName .Name $.Prefix}}:
		@{{.FuncName}}(attrs)
{{end}}	}
}

// IconExists checks if an icon name is valid
func IconExists(name string) bool {
	switch IconName(name) {
{{range .Icons}}	case {{call $.ToConstantName .Name $.Prefix}}:
		return true
{{end}}	default:
		return false
	}
}

// AllIcons returns all available icon names
func AllIcons() []IconName {
	return []IconName{
{{range .Icons}}		{{call $.ToConstantName .Name $.Prefix}},
{{end}}	}
}

// IconCount returns the total number of available icons
func IconCount() int {
	return {{len .Icons}}
}

// IconByName returns the IconName for a string name if it exists
func IconByName(name string) (IconName, bool) {
	iconName := IconName(name)
	if IconExists(name) {
		return iconName, true
	}
	return "", false
}`

// Template for search functionality
const searchTemplate = `// Code generated by lucide-templ-gen on {{.Timestamp}}. DO NOT EDIT.

package {{.PackageName}}

// SearchResult represents a search result with relevance scoring
type SearchResult struct {
	IconName  IconName
	Relevance int // Higher is more relevant
	MatchType string // "exact", "tag", "partial"
}

// IconSearch provides search and filter functionality for icons
type IconSearch struct {
	icons []IconSearchData
	tagIndex map[string][]IconName
}

// IconSearchData contains searchable metadata for an icon
type IconSearchData struct {
	Name       IconName
	Tags       []string
	AllText    string // Pre-computed search text for efficiency
}

// NewIconSearch creates a new search instance with precomputed indexes
func NewIconSearch() *IconSearch {
	search := &IconSearch{
		icons: []IconSearchData{
{{range .Icons}}			{
				Name:       {{call $.ToConstantName .Name $.Prefix}},
				Tags:       []string{{"{"}}{{range .Tags}}"{{.}}", {{end}}{{"}"}},
				AllText:    strings.ToLower("{{.Name}} {{join .Tags " "}}"),
			},
{{end}}		},
		tagIndex:      make(map[string][]IconName),
	}
	
	search.buildIndexes()
	return search
}

// buildIndexes creates lookup indexes for faster searching
func (s *IconSearch) buildIndexes() {
	for _, icon := range s.icons {
		// Build tag index
		for _, tag := range icon.Tags {
			tagKey := strings.ToLower(tag)
			s.tagIndex[tagKey] = append(s.tagIndex[tagKey], icon.Name)
		}
	}
}

// Search performs incremental search across icon names and tags
func (s *IconSearch) Search(query string) []SearchResult {
	if query == "" {
		return s.getAllIcons()
	}
	
	query = strings.ToLower(strings.TrimSpace(query))
	var results []SearchResult
	seen := make(map[IconName]bool)
	
	// 1. Exact name matches (highest relevance)
	for _, icon := range s.icons {
		if strings.ToLower(string(icon.Name)) == query {
			results = append(results, SearchResult{
				IconName:  icon.Name,
				Relevance: 100,
				MatchType: "exact",
			})
			seen[icon.Name] = true
		}
	}
	
	// 2. Exact tag matches
	if icons, exists := s.tagIndex[query]; exists {
		for _, iconName := range icons {
			if !seen[iconName] {
				results = append(results, SearchResult{
					IconName:  iconName,
					Relevance: 90,
					MatchType: "tag",
				})
				seen[iconName] = true
			}
		}
	}
	
	// 3. Partial matches in names and tags
	for _, icon := range s.icons {
		if !seen[icon.Name] && strings.Contains(icon.AllText, query) {
			relevance := s.calculatePartialRelevance(icon, query)
			if relevance > 0 {
				results = append(results, SearchResult{
					IconName:  icon.Name,
					Relevance: relevance,
					MatchType: "partial",
				})
			}
		}
	}
	
	// Sort by relevance (highest first)
	sort.Slice(results, func(i, j int) bool {
		return results[i].Relevance > results[j].Relevance
	})
	
	return results
}

// SearchByTag returns all icons with a specific tag
func (s *IconSearch) SearchByTag(tag string) []IconName {
	if icons, exists := s.tagIndex[strings.ToLower(tag)]; exists {
		result := make([]IconName, len(icons))
		copy(result, icons)
		return result
	}
	return []IconName{}
}

// GetAllTags returns all available tags sorted alphabetically
func (s *IconSearch) GetAllTags() []string {
	tags := make([]string, 0, len(s.tagIndex))
	for tag := range s.tagIndex {
		tags = append(tags, tag)
	}
	sort.Strings(tags)
	return tags
}

// GetTagsForIcon returns all tags for a specific icon
func (s *IconSearch) GetTagsForIcon(iconName IconName) []string {
	for _, icon := range s.icons {
		if icon.Name == iconName {
			result := make([]string, len(icon.Tags))
			copy(result, icon.Tags)
			return result
		}
	}
	return []string{}
}

// GetIconCount returns the total number of searchable icons
func (s *IconSearch) GetIconCount() int {
	return len(s.icons)
}

// calculatePartialRelevance calculates relevance score for partial matches
func (s *IconSearch) calculatePartialRelevance(icon IconSearchData, query string) int {
	iconName := strings.ToLower(string(icon.Name))
	
	// Name starts with query - high relevance
	if strings.HasPrefix(iconName, query) {
		return 70
	}
	
	// Name contains query - medium relevance
	if strings.Contains(iconName, query) {
		return 60
	}
	
	// Tag starts with query - medium relevance
	for _, tag := range icon.Tags {
		if strings.HasPrefix(strings.ToLower(tag), query) {
			return 50
		}
	}
	
	// Tag contains query - lower relevance
	for _, tag := range icon.Tags {
		if strings.Contains(strings.ToLower(tag), query) {
			return 40
		}
	}
	
	return 0
}

// getAllIcons returns all icons with default relevance
func (s *IconSearch) getAllIcons() []SearchResult {
	results := make([]SearchResult, len(s.icons))
	for i, icon := range s.icons {
		results[i] = SearchResult{
			IconName:  icon.Name,
			Relevance: 50,
			MatchType: "all",
		}
	}
	return results
}

// SearchOptions provides configuration for search behavior
type SearchOptions struct {
	MaxResults int
	MinRelevance int
	Tags []string // Filter by specific tags
}

// SearchWithOptions performs search with additional filtering options
func (s *IconSearch) SearchWithOptions(query string, options SearchOptions) []SearchResult {
	results := s.Search(query)
	
	// Apply tag filter
	if len(options.Tags) > 0 {
		filtered := []SearchResult{}
		tagSet := make(map[string]bool)
		for _, tag := range options.Tags {
			tagSet[strings.ToLower(tag)] = true
		}
		
		for _, result := range results {
			iconTags := s.GetTagsForIcon(result.IconName)
			for _, tag := range iconTags {
				if tagSet[strings.ToLower(tag)] {
					filtered = append(filtered, result)
					break
				}
			}
		}
		results = filtered
	}
	
	// Apply minimum relevance filter
	if options.MinRelevance > 0 {
		filtered := []SearchResult{}
		for _, result := range results {
			if result.Relevance >= options.MinRelevance {
				filtered = append(filtered, result)
			}
		}
		results = filtered
	}
	
	// Apply max results limit
	if options.MaxResults > 0 && len(results) > options.MaxResults {
		results = results[:options.MaxResults]
	}
	
	return results
}

// GetSearchResultIcons returns search results as a slice of icon components
func (s *IconSearch) GetSearchResultIcons(query string, attrs templ.Attributes) []templ.Component {
	results := s.Search(query)
	icons := make([]templ.Component, len(results))
	for i, result := range results {
		icons[i] = Icon(result.IconName, attrs)
	}
	return icons
}

// GetTagIcons returns all icons with a specific tag as a slice of components
func (s *IconSearch) GetTagIcons(tag string, attrs templ.Attributes) []templ.Component {
	iconNames := s.SearchByTag(tag)
	icons := make([]templ.Component, len(iconNames))
	for i, iconName := range iconNames {
		icons[i] = Icon(iconName, attrs)
	}
	return icons
}

// GetAllIconComponents returns all available icons as a slice of components
func (s *IconSearch) GetAllIconComponents(attrs templ.Attributes) []templ.Component {
	allResults := s.getAllIcons()
	icons := make([]templ.Component, len(allResults))
	for i, result := range allResults {
		icons[i] = Icon(result.IconName, attrs)
	}
	return icons
}`

// TemplateData holds data for template execution
type TemplateData struct {
	PackageName      string
	Prefix           string
	Icons            []IconData
	Timestamp        string
	ToConstantName   func(string, string) string
	Join             func([]string, string) string
}

// generateIconsFile creates the main icons template file
func generateIconsFile(icons []IconData, config Config, outputPath string) error {
	data := TemplateData{
		PackageName: config.PackageName,
		Prefix:      config.Prefix,
		Icons:       icons,
		Timestamp:   time.Now().Format(time.RFC3339),
		Join:        joinStrings,
	}

	tmpl := template.Must(template.New("icons").Parse(iconsTemplate))
	
	file, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer file.Close()

	return tmpl.Execute(file, data)
}

// generateRegistryFile creates the icon registry file
func generateRegistryFile(icons []IconData, config Config, outputPath string) error {
	data := TemplateData{
		PackageName:    config.PackageName,
		Prefix:         config.Prefix,
		Icons:          icons,
		Timestamp:      time.Now().Format(time.RFC3339),
		ToConstantName: toConstantName,
		Join:           joinStrings,
	}

	tmpl := template.Must(template.New("registry").Parse(registryTemplate))
	
	file, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer file.Close()

	return tmpl.Execute(file, data)
}

// joinStrings joins a slice of strings with a separator
func joinStrings(slice []string, sep string) string {
	return strings.Join(slice, sep)
}

// generateSearchFile creates the search functionality file
func generateSearchFile(icons []IconData, config Config, outputPath string) error {
	data := TemplateData{
		PackageName:    config.PackageName,
		Prefix:         config.Prefix,
		Icons:          icons,
		Timestamp:      time.Now().Format(time.RFC3339),
		ToConstantName: toConstantName,
		Join:           joinStrings,
	}

	tmpl := template.Must(template.New("search").Funcs(template.FuncMap{
		"join": joinStrings,
	}).Parse(searchTemplate))
	
	file, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer file.Close()

	return tmpl.Execute(file, data)
}
